version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: reza_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reza_network

  springboot:
    image: openjdk:17
    container_name: reza_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - postgres
    networks:
      - reza_network

volumes:
  postgres_data:

networks:
  reza_network:
    driver: bridge