services:
  postgres:
    image: postgres:13
    container_name: reza_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reza_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: reza_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - reza_network

volumes:
  postgres_data:

networks:
  reza_network:
    driver: bridge
