version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: reza_db
    environment:
      POSTGRES_DB: reza
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reza_network

  springboot:
    image: openjdk:17
    container_name: reza_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reza
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - reza_network

volumes:
  postgres_data:

networks:
  reza_network:
    driver: bridge